### PR TITLE
First attempt at blurring transparency

### PR DESCRIPTION
**Pull request by adamazing**
Attempt at implementing blurred transparent background for alacritty 

(https://github.com/alacritty/alacritty/issues/972)

### CODE REVIEW

**Comment by samrathchadha** [comment]
Compiling this and testing it on macOS as soon as I get back to my computer

**Comment by tctien342** [comment]
Seem like it not working correctly on macOS
### Config
+ MacOS 12.4
+ MBP 14 M1 2021 + ARM64 rust

```yaml
window:
  dimensions:
    columns: 100
    lines: 100

  padding:
    x: 6
    y: 6

  decorations: buttonless
  dynamic_padding: true
  blur_background: blur
  startup_mode: Maximized
  opacity: 0.95
```

Screen Shot 2022-05-25 at 13 52 27

> Terminal still response when typing, type `exit` still exit the app, the problem seem to render failed

**Comment by samrathchadha** [comment]
Yup same for me

**Comment by adamazing** [comment]
Yep. Sorry, I think some context was lost in the discussion on the alacritty/alacritty repo issue, or my communication was not sufficient. 

This is a WIP in my fork; I was trying out the `window-vibrancy` crate to see if it provided an easy path to blurred opacity backgrounds in alacritty but either it or, more likely, my ability to marshall it, is not all the way there yet.  

I will continue to work at it when I can find time; thanks to you both for testing 🙇‍♂️

**Comment by tctien342** [comment]
Nah, it's okay man. We just wanna try it. I have used `window-vibrancy` package on my tauri app and it works very well. Maybe it has been a conflict with Alacritty's render function

**Comment by samrathchadha** [comment]
it seems like it blurs over the text weirdly enough

**Comment by vada-pav** [comment]
@adamazing  have you gotten it to work properly yet? and could you please tell me how to blur my alacritty window as well?

**Pull request closed without merging**
